services:
  - type: web
    name: citypulse-ml-api
    env: python
    pythonVersion: "3.9.18"   # Explicitly sets the Python version
    rootDir: ./Python         # Sets the working directory to your Python folder
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ml_server:app"
    
