// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPEYlmUYHoiHJfenBTRuA6Gs7klfyHTeE',
    appId: '1:209480732477:web:bae888e26d39e606ea7f54',
    messagingSenderId: '209480732477',
    projectId: 'map-app-abc',
    authDomain: 'map-app-abc.firebaseapp.com',
    storageBucket: 'map-app-abc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCsjhUHgk4VahbU548_pdXs9M8j-G5jI',
    appId: '1:209480732477:android:1bda5a29debe922bea7f54',
    messagingSenderId: '209480732477',
    projectId: 'map-app-abc',
    storageBucket: 'map-app-abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wwMJxBE_qbyjOImFA1eWDFWB4JV6XKA',
    appId: '1:209480732477:ios:e6f2f43339cee3cdea7f54',
    messagingSenderId: '209480732477',
    projectId: 'map-app-abc',
    storageBucket: 'map-app-abc.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0wwMJxBE_qbyjOImFA1eWDFWB4JV6XKA',
    appId: '1:209480732477:ios:e6f2f43339cee3cdea7f54',
    messagingSenderId: '209480732477',
    projectId: 'map-app-abc',
    storageBucket: 'map-app-abc.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPEYlmUYHoiHJfenBTRuA6Gs7klfyHTeE',
    appId: '1:209480732477:web:d808fab80a82452aea7f54',
    messagingSenderId: '209480732477',
    projectId: 'map-app-abc',
    authDomain: 'map-app-abc.firebaseapp.com',
    storageBucket: 'map-app-abc.firebasestorage.app',
  );
}
